services:
  - type: web
    name: money-in-plain-english-app
    runtime: node
    plan: starter
    rootDir: app
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /var/data/dev.sqlite3
      - key: SESSION_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: SENTRY_DSN
        value: ""
        sync: false
